### ISSUE TITLE
登录后一直转圈，不能跳转到主页

### ISSUE THREAD

**Issue by kkAShyia** [XuYang8026/UniversalProject#1]
登录成功后，一直转圈，然后又返回到登录页，不能跳转到主页。
---原因是我配置的本地服务器接口，屏蔽掉登录模块就好，稍后我会在代码中去掉

**Comment by XuYang8026** [comment]
---原因是我配置的本地服务器接口，屏蔽掉登录模块就好，稍后我会在代码中去掉
