### ISSUE TITLE
图片上传出错

### ISSUE THREAD

**Issue by BadDeveloper2022** [XuYang8026/UniversalProject#11]
图片上传方法报错 
Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: text/html" UserInfo={NSLocalizedDescription=Request failed: unacceptable content-type: text/html, NSErrorFailingURLKey=http://www.chuantu.biz/upload.php
网上的解决办法，我看你已经添加了text-html,但是还是不行

还有一个问题：Http 封装的时候，有时候json返回的，有时候html或者纯文字返回的怎么调？

**Comment by XuYang8026** [comment]
1. 用的是哪个网络库上传图片的？是YTK吗？
2. 返回的数据类型都是data，至于你要转成什么，完全看你自己，通常来讲，如果APP返回都是JSON，那我会在封装网络库的时候就把它转成字典，供调用者直接使用，而你这种情况，网络库并不确定返回值的类型时，建议直接抛出Data，调用者自行转换

**Comment by RondaHe** [comment]
AFN3.0使用AFHTTPSessionManager来发起请求。给manager设置不同的responseSerializer返回不同的数据格式
AFHTTPResponseSerializer           二进制格式 返回NSData，可以自己转换json或原始NSString
AFJSONResponseSerializer           JSON     返回json字典

**Comment by ronanhardiman** [comment]
有Swift版本的么？听说现在新的项目大都用Swift开发的。

**Comment by XuYang8026** [comment]
暂时没有Swift版本，未来可能会出。
