### ISSUE TITLE
jsCalliOSDelegate?

### ISSUE THREAD

**Issue by BadDeveloper2022** [XuYang8026/UniversalProject#12]
我自己稍微改了XLJSHandler ，写了一个委托，把jS的事件传递给当前的ViewController。
这样实际开发中更有用了
@protocol IWebViewJSActionResultsDelegate <NSObject>
- (void)jsCalliOS:(NSString*)name andData:(id)data; //JS Call iOS
@end

**Comment by XuYang8026** [comment]
6666
