### ISSUE TITLE
push跳转时tab bar的问题

### ISSUE THREAD

**Issue by hy151264** [XuYang8026/UniversalProject#8]
在iPhone X模拟器中，push跳转的时候，例如：我的界面中点击设置进行push，tabbar整体会突然向上移动一下。

**Comment by XuYang8026** [comment]
已兼容，感觉是系统的bug，用的系统TabBar都会出这个问题

**Comment by cmconan** [comment]
在iPhone X模拟器中，present弹出页面跳转（"Demo" - "11-JS与Native交互"）再返回之后，再push跳转（"Demo" - "12-轮播）时tabbar整个高度变成了49，整体又向下移动了。

**Comment by XuYang8026** [comment]
多谢各位提的Bug，现已经修复该问题。
