### ISSUE TITLE
YTKNetwork的使用

### ISSUE THREAD

**Issue by Aaron-Fan** [XuYang8026/UniversalProject#9]
可以用真实的URL地址测一下数据，

或者能给能出一个YTKNetwork 详细的使用开源项目吗？

**Comment by XuYang8026** [comment]
忙完这段时间会对框架进行大更新，我会找个地址来示范如何在实战中使用YTKNerwork。不过，这也许会有点久，可能两周，也可能一个月，建议你先自己尝试一下吧

**Comment by Aaron-Fan** [comment]
谢谢作者，我先尝试YTKNetwork，同时也期待你更新后的框架！
